services:

  api:
    image: harbor-registry.whoi.edu/amplify/mediastore:latest
    command: ./start-django test
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 33300:8000
    depends_on:
      - db
      - nginx

  db:
    image: postgres:17-alpine
    volumes:
      - ./vols/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped


volumes:
  static_volume: