services:

  api:
    image: harbor-registry.whoi.edu/amplify/mediastore:latest
    command: ./start-django test
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - nginx

  db:
    image: postgres:17-alpine
    volumes:
      - ./vols/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./vols/nginx/logs:/var/log/nginx
      - ${SSL_CERT}:/ssl/ssl.pem:ro
      - ${SSL_KEY}:/ssl/ssl.key:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "100m" # file size

volumes:
  static_volume: