#!/bin/sh

python manage.py makemigrations
python manage.py migrate
#python manage.py collectstatic --no-input

python manage.py test
# don't actually start the server
# python manage.py runserver 0.0.0.0:8000
